from random import *
print(random())
print(random())
print(random())
print(random())
print(random())
print(random())

print(randrange(10))
print(randrange(10))
print(randrange(10))
print(randrange(10))
print(randrange(10))
print(randrange(10))
print("")
print(randint(1,10))
print(randint(1,10))
print(randint(1,10))
print(randint(1,10))
print(randint(1,10))
print(randint(1,10))